### ISSUE TITLE
Reinitialising of ICStation relay cards causes unwanted state changes

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/avx#52]
The initialise() method of the ICStation relay cards sends two bytes to the card, which is needed for the card to start responding to on/off commands.

However, if initialise() is called again, these same commands change the state of the relays.

This is unfortunate, since initialise() is called when the avx-controller starts up and at the completion of the system-power-on cycle of staldates/av-control.

We can't always know if the card has been initialised (e.g. by a previous avx process) but we should do our best and remember if a card has been initialised or not.

**Comment by rjmunro** [comment]
I guess there's no way to reset the cards and send the initialisation bytes again?

**Comment by jamesremuscat** [comment]
No, that would make life too easy ;-)
