### ISSUE TITLE
Support custom logging configuration

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/avx#60]
At the moment, our Python logging configuration is hardcoded in `Controller.py`.

It should be possible to specify logging options in a controller's config file, say under the key `logging`. We should pass the dict straight through to [logging.config.dictConfig](https://docs.python.org/2/library/logging.config.html#logging.config.dictConfig).

The -d / --debug flag should continue to work, and we should have sensible defaults in case no other options are provided (and for before the configuration is loaded).

(Motivation: being able to log to syslog, and hence be able to monitor via papertrail etc.)

**Comment by rjmunro** [comment]
Logging to Papertrail sounds like a cool idea.

**Comment by jamesremuscat** [comment]
In order to simplify implementation, by "continue to work" I mean that the presence of the debug flag should mean that the default logger level should be set to "DEBUG", overriding what is specified in the configuration file if necessary.

There's no way of knowing what arbitrary logging configuration the user might have specified, and if they've gone to the trouble of configuring their own logging then it's not too strenuous for them to adjust its levels if needed.
